fix bug for mongodb
Fixing bug:
loopback-example-access-control\server\boot\sample-models.js:31
        if (err) throw err;
                 ^
ValidationError: The `team` instance is not valid. Details: `memberId` can't be blank (v
alue: NaN).,ValidationError: The `team` instance is not valid. Details: `memberId` can't
be blank (value: NaN).

Caused by changing datasource from memory to mongodb.
In mongodb, type of id is string, not number.